# Generated by Django 4.1.6 on 2023-02-04 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="sectors_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("value", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="form_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "sector",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.sectors_list",
                    ),
                ),
            ],
        ),
    ]
